### ISSUE TITLE
no executable "static void Main(string[] args)"   in the project 

### ISSUE THREAD

**Issue by mM-009** [cmorterud/GeneticAlgorithm#1]
there is no executable project as in          "static void Main(string[] args)"  in this project ?

**Comment by cmorterud** [comment]
Hello! This is meant to be imported as a library. I did not think it made sense to have a main.

**Comment by mM-009** [comment]
Including a sample main would be helpful to understand how to use the functions in the library.

**Comment by cmorterud** [comment]
Yes, you can look in the test file for an understanding of the library!
